# Generated by Django 3.2 on 2022-12-06 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 16, 21, 37, 260961), verbose_name='Дата'),
        ),
    ]
