# Generated by Django 3.2 on 2022-12-11 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 17, 27, 52, 496249), verbose_name='Дата'),
        ),
    ]
