# Generated by Django 3.2 on 2022-12-06 14:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название')),
                ('amount', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Фрукт',
                'verbose_name_plural': 'Фрукты',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SS', 'Success'), ('ER', 'Error')], default='SS', max_length=2, verbose_name='Статус')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 12, 6, 16, 21, 37, 262571), verbose_name='Дата')),
                ('amount', models.IntegerField(verbose_name='Кол-во фруктов')),
                ('usd', models.IntegerField(verbose_name='Сумма USD')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruits.fruit', verbose_name='Фрукт')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ['-date'],
            },
        ),
    ]
