# Generated by Django 3.2 on 2022-12-07 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruit',
            options={'ordering': ['name'], 'verbose_name': 'Фрукт', 'verbose_name_plural': 'Фрукты'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['date'], 'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 22, 56, 24, 108218), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('SS', 'SUCCESS'), ('ER', 'ERROR')], default='SS', max_length=2, verbose_name='Статус'),
        ),
    ]
