# Generated by Django 3.2 on 2022-12-08 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_auto_20221207_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 23, 19, 54, 579039), verbose_name='Дата'),
        ),
    ]
