# Generated by Django 3.2 on 2022-12-10 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0003_alter_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 18, 16, 39, 80942), verbose_name='Дата'),
        ),
    ]
