# Generated by Django 3.2 on 2022-12-11 12:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0004_alter_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 14, 42, 44, 94939), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='log',
            name='fruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='fruits.fruit', verbose_name='Фрукт'),
        ),
    ]
