# Generated by Django 3.2 on 2022-12-11 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0005_auto_20221211_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='operation',
            field=models.CharField(choices=[('B', 'BUY'), ('S', 'SELL')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 17, 27, 52, 500078), verbose_name='Дата'),
        ),
    ]
